### PR TITLE
Update apo.obo

### PR DESCRIPTION
**Pull request by suzialeksander**
Updating file headers.  Looking at https://owlcollab.github.io/oboformat/doc/obo-syntax.html I think the last change from 'null mutant' to 'null' is an EXACT synonym, so no other changes.  @matentzn is there anything else in this file I should update (since it hasn't been touched in 5 years)

### CODE REVIEW

**Comment by matentzn** [comment]
There are a bunch of things that you _could_ be doing, for example:
Adding the correct OBO ontology metadata (see [here](https://github.com/INCATools/ontology-development-kit/blob/master/docs/License.md#obo-example) for an example).

You should also add your own apo.owl and apo.json artefacts here. Are you familiar with using ROBOT?

**Comment by suzialeksander** [comment]
Hi @matentzn, I'll work on fixing our metadata.  Is the update to the data/name ok, or should I fix all the metadata and the date in a new PR?

**Comment by matentzn** [comment]
Its totally fine; we dont really use `saved-by` really, but why not. I think these changes are correct! You can fix the rest in this PR, or another - it does not matter!

**Comment by suzialeksander** [comment]
OK, I'm going to try and fix the rest in a different pull.  Can you merge this and I'll put the format changes on a new branch, thanks

**Comment by matentzn** [comment]
I am not sure I am the right person to merge this! I have not much to do with apo! :)

**Comment by suzialeksander** [comment]
Actually I'll just make a new PR, nevermind & thanks!

**Pull request closed without merging**
